Adding optimized configuration file generation ADR
GetKompile/kompile pull request #1
Opened 2023-10-05 14:03 UTC by ndthanhit

Adding optimized configuration file generation ADR

2023-10-06 05:45 UTC, agibsonccc requested changes

2023-10-06 05:45 UTC, agibsonccc commented on kompile.iml
> +        <option value="$MODULE_DIR$/src/main/ops" />
@ndthanhit can you actually put intellij related files on .gitignore?

2023-10-06 05:45 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +Proposed by: Adam Gibson (10-05-2023)
@ndthanhit change this to your name and date

2023-10-06 05:45 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +Discussed with: N/A
The discussed with is me.

2023-10-06 05:45 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +- Graalvm native-image build tool use some configuration files to solve with dynamic aspects of the application such as: reflection, jni, resources...
Run this through a tool like grammarly to improve the english here please.

2023-10-06 05:45 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +   Define a main class: In this class, The main method will load all the classes which extends ConfigurationGenerator run them with the agent embedded, check if any classes which use reflection or jn
@ndthanhit rather than list features describe how it will work and if possible show sample code. You can see more of this in the dl4j ADRs.

2023-10-06 10:19 UTC, agibsonccc requested changes

2023-10-06 10:19 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +- Therefore, we plan to have a "tool" which will generate these configuration files with two objectives: automatic and efficient.
Present tense here.  Present what the tool does and how it works.

2023-10-06 10:19 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +1. For classes inside Kompile, define our own annotation. Create a configuration file and add all needed classes so that the agent can include them into .json configuration files.
The manual approach would be an addon to the automatic approach we pick. Separate this out.

2023-10-06 10:19 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +   &nbsp;&nbsp;&nbsp;&nbsp;@Autowired \
Remove the spring specific concepts here. We either use quarkus or picocli here to inject fields. Quarkus uses @Inject. If you want to use dependency injection explain why.

2023-10-06 10:19 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +$JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=/home/temp/ -jar kompile-1.0-SNAPSHOT.jar.jar
Elaborate on a concrete example of a runner. Have a specific concrete target. Focus on looking at one of the commands and use the command in a class. It could also be a set of commands that are run. Ideally runners are comprehensive running a set of commands that simulate real world usage. We would separate that by cpu/gpu ( a backend for each cli)

2023-10-06 14:22 UTC, ndthanhit commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +1. For classes inside Kompile, define our own annotation. Create a configuration file and add all needed classes so that the agent can include them into .json configuration files.
What do you mean by manual approach? You mean creating configuration file and add all needed classes is the manual part? Actually I am thinking that do we really need this manual part. We just can try with the automatic part to see if they can include the classes in Kompile. If yes, we don't have to do this manual part.

2023-10-06 14:41 UTC, ndthanhit commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +$JAVA_HOME/bin/java -agentlib:native-image-agent=config-output-dir=/home/temp/ -jar kompile-1.0-SNAPSHOT.jar.jar
Actually my idea is we have two options here, firstly we can use commands in .sh file to run all the commands. Or we can create a class that can load and run all commands. Will change the ADR according that.

2023-10-06 14:42 UTC, ndthanhit commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +1. For classes inside Kompile, define our own annotation. Create a configuration file and add all needed classes so that the agent can include them into .json configuration files.
And also this approach is more difficult than the 2nd one, so I will change their position and rewrite them a little bit next Monday.

2023-10-17 04:27 UTC, agibsonccc requested changes

2023-10-17 04:27 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +### Second option: Run sub-process runners inside a parent process
Replace this with an actual design. No POC concept should ever be put in an ADR. It's purely for learning purposes. Anything outside the final design should be referenced as part of the implementation but not included here. Focus on the abstraction.

2023-10-17 07:17 UTC, agibsonccc reviewed
Redo it again please.

2023-10-17 07:17 UTC, agibsonccc commented on ADRs/Optimized Configuration Files Generation - 0004.md
> +   public class Nd4jRunner implements BasedRunner { \
Change the runner to something a bit more descriptive. ConfigGeneratorRunner should be fine. Change run to generateConfigFiles(); 

You're still missing the sub porcess architecture.  This misses the implementation we discussed for a generic tool that can take in a runner class and run it via a subprocess. You don't really describe the implementation. You're also missing details like how we inject the classpath.

2023-10-18 12:47 UTC, agibsonccc approved these changes

2023-10-18 12:47 UTC, merged